create table if not exists public.published_offers (
  id bigint generated by default as identity primary key,
  offer_key text not null,
  network text not null,
  offer_id text not null,
  channel text not null,
  external_id text,
  published_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint published_offers_offer_channel_unique unique (offer_key, channel)
);

create index if not exists published_offers_published_at_idx
  on public.published_offers (published_at desc);

alter table public.published_offers enable row level security;

revoke all on public.published_offers from anon, authenticated;
