-- Affiliate Content Automation: complete service-only database foundation.

-- 0) Core automation tables. These CREATE IF NOT EXISTS statements also make
-- this migration reproducible on a fresh project, because the first database
-- bootstrap was initially created directly in Supabase before migrations existed.
create table if not exists public.automation_rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  enabled boolean not null default true,
  networks text[] not null default array['shopee']::text[],
  channels text[] not null default array['telegram']::text[],
  keyword text not null,
  category text,
  min_commission numeric,
  min_discount numeric,
  max_price numeric,
  quantity smallint not null default 5,
  sort text,
  avoid_repeat_days smallint not null default 7,
  schedule_cron text,
  timezone text not null default 'America/Sao_Paulo',
  dry_run boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint automation_rules_quantity_check check (quantity >= 1 and quantity <= 100),
  constraint automation_rules_avoid_repeat_days_check check (avoid_repeat_days >= 0 and avoid_repeat_days <= 365),
  constraint automation_rules_sort_check check (sort is null or sort in ('commission', 'price', 'sales', 'discount'))
);

create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  rule_id uuid references public.automation_rules(id) on delete set null,
  trigger_source text not null default 'manual',
  status text not null default 'running',
  dry_run boolean not null default true,
  requested_count integer not null default 0,
  selected_count integer not null default 0,
  queued_count integer not null default 0,
  published_count integer not null default 0,
  skipped_count integer not null default 0,
  failed_count integer not null default 0,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  constraint automation_runs_trigger_source_check check (trigger_source in ('manual', 'scheduler', 'api', 'test')),
  constraint automation_runs_status_check check (status in ('running', 'completed', 'partial', 'failed', 'cancelled'))
);

create index if not exists automation_runs_rule_started_idx
  on public.automation_runs (rule_id, started_at desc);
create index if not exists automation_runs_status_started_idx
  on public.automation_runs (status, started_at desc);

create table if not exists public.publication_queue (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.automation_runs(id) on delete set null,
  rule_id uuid references public.automation_rules(id) on delete set null,
  offer_key text not null,
  network text not null,
  offer_id text not null,
  channel text not null,
  status text not null default 'pending',
  priority smallint not null default 100,
  scheduled_for timestamptz not null default now(),
  available_at timestamptz not null default now(),
  attempts smallint not null default 0,
  max_attempts smallint not null default 3,
  locked_at timestamptz,
  locked_by text,
  content jsonb not null default '{}'::jsonb,
  offer_snapshot jsonb not null default '{}'::jsonb,
  external_id text,
  last_error text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint publication_queue_attempts_check check (attempts >= 0),
  constraint publication_queue_max_attempts_check check (max_attempts >= 1 and max_attempts <= 20),
  constraint publication_queue_status_check check (status in (
    'pending', 'processing', 'retry', 'published', 'failed', 'skipped_duplicate', 'cancelled'
  ))
);

create index if not exists publication_queue_locked_idx
  on public.publication_queue (locked_at)
  where status = 'processing';
create index if not exists publication_queue_run_idx
  on public.publication_queue (run_id, created_at desc);
create unique index if not exists publication_queue_run_offer_channel_unique
  on public.publication_queue (run_id, offer_key, channel)
  where run_id is not null;
create index if not exists publication_queue_worker_idx
  on public.publication_queue (status, available_at, priority, scheduled_for)
  where status in ('pending', 'retry');

-- 1) Persistent publication history used by the current deduplication engine.
create table if not exists public.published_offers (
  id bigint generated by default as identity primary key,
  source_queue_id uuid references public.publication_queue(id) on delete set null,
  run_id uuid references public.automation_runs(id) on delete set null,
  rule_id uuid references public.automation_rules(id) on delete set null,
  offer_key text not null,
  network text not null,
  offer_id text not null,
  channel text not null,
  external_id text,
  published_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

-- Compatibility with the legacy 0001 migration, which may have already
-- created published_offers with fewer columns and a permanent uniqueness rule.
alter table public.published_offers
  add column if not exists source_queue_id uuid references public.publication_queue(id) on delete set null;
alter table public.published_offers
  add column if not exists run_id uuid references public.automation_runs(id) on delete set null;
alter table public.published_offers
  add column if not exists rule_id uuid references public.automation_rules(id) on delete set null;
alter table public.published_offers
  drop constraint if exists published_offers_offer_channel_unique;

create unique index if not exists published_offers_source_queue_unique
  on public.published_offers (source_queue_id)
  where source_queue_id is not null;
create index if not exists published_offers_dedupe_idx
  on public.published_offers (offer_key, channel, published_at desc);
create index if not exists published_offers_offer_idx
  on public.published_offers (network, offer_id, published_at desc);

-- offer_key + channel is intentionally NOT unique. The same offer may be
-- republished after avoid_repeat_days and every publication must remain in history.

-- 2) Publication audit log.
create table if not exists public.publication_logs (
  id bigint generated by default as identity primary key,
  queue_id uuid references public.publication_queue(id) on delete cascade,
  run_id uuid references public.automation_runs(id) on delete set null,
  rule_id uuid references public.automation_rules(id) on delete set null,
  event text not null,
  status text,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists publication_logs_queue_created_idx
  on public.publication_logs (queue_id, created_at desc);
create index if not exists publication_logs_run_created_idx
  on public.publication_logs (run_id, created_at desc);

-- 3) Stronger queue idempotency and lookup indexes.
alter table public.publication_queue
  add column if not exists idempotency_key text;

create unique index if not exists publication_queue_idempotency_unique
  on public.publication_queue (idempotency_key)
  where idempotency_key is not null;
create index if not exists publication_queue_rule_status_idx
  on public.publication_queue (rule_id, status, scheduled_for desc);
create index if not exists automation_rules_enabled_idx
  on public.automation_rules (enabled)
  where enabled = true;

-- 4) Validation constraints that were not part of the initial bootstrap.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'automation_rules_min_commission_check') then
    alter table public.automation_rules
      add constraint automation_rules_min_commission_check
      check (min_commission is null or min_commission >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'automation_rules_min_discount_check') then
    alter table public.automation_rules
      add constraint automation_rules_min_discount_check
      check (min_discount is null or (min_discount >= 0 and min_discount <= 100));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'automation_rules_max_price_check') then
    alter table public.automation_rules
      add constraint automation_rules_max_price_check
      check (max_price is null or max_price >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'automation_rules_networks_check') then
    alter table public.automation_rules
      add constraint automation_rules_networks_check
      check (cardinality(networks) > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'automation_rules_channels_check') then
    alter table public.automation_rules
      add constraint automation_rules_channels_check
      check (cardinality(channels) > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'publication_queue_priority_check') then
    alter table public.publication_queue
      add constraint publication_queue_priority_check
      check (priority >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'automation_runs_counts_check') then
    alter table public.automation_runs
      add constraint automation_runs_counts_check
      check (
        requested_count >= 0 and selected_count >= 0 and queued_count >= 0 and
        published_count >= 0 and skipped_count >= 0 and failed_count >= 0
      );
  end if;
end $$;

-- 5) Consistent updated_at maintenance.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists automation_rules_set_updated_at on public.automation_rules;
create trigger automation_rules_set_updated_at
before update on public.automation_rules
for each row execute function public.set_updated_at();

drop trigger if exists publication_queue_set_updated_at on public.publication_queue;
create trigger publication_queue_set_updated_at
before update on public.publication_queue
for each row execute function public.set_updated_at();

-- 6) Recover jobs abandoned by a crashed worker.
create or replace function public.recover_stale_publications(
  p_lock_timeout_minutes integer default 10
)
returns integer
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  recovered_count integer := 0;
begin
  if p_lock_timeout_minutes < 1 or p_lock_timeout_minutes > 1440 then
    raise exception 'p_lock_timeout_minutes must be between 1 and 1440';
  end if;

  with recovered as (
    update public.publication_queue q
    set
      status = case when q.attempts >= q.max_attempts then 'failed' else 'retry' end,
      available_at = case when q.attempts >= q.max_attempts then q.available_at else now() end,
      locked_at = null,
      locked_by = null,
      last_error = coalesce(q.last_error, 'worker lock expired'),
      updated_at = now()
    where q.status = 'processing'
      and q.locked_at is not null
      and q.locked_at < now() - make_interval(mins => p_lock_timeout_minutes)
    returning q.id, q.run_id, q.rule_id, q.status
  )
  insert into public.publication_logs (queue_id, run_id, rule_id, event, status, message)
  select id, run_id, rule_id, 'lock_recovered', status, 'stale worker lock recovered'
  from recovered;

  get diagnostics recovered_count = row_count;
  return recovered_count;
end;
$$;

-- 7) Atomically claim due queue items with SKIP LOCKED for safe concurrent workers.
create or replace function public.claim_due_publications(
  p_worker_id text,
  p_limit integer default 10
)
returns setof public.publication_queue
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if p_worker_id is null or btrim(p_worker_id) = '' then
    raise exception 'p_worker_id is required';
  end if;
  if p_limit < 1 or p_limit > 100 then
    raise exception 'p_limit must be between 1 and 100';
  end if;

  return query
  with candidates as (
    select q.id
    from public.publication_queue q
    where q.status in ('pending', 'retry')
      and q.scheduled_for <= now()
      and q.available_at <= now()
      and q.attempts < q.max_attempts
    order by q.priority asc, q.scheduled_for asc, q.created_at asc
    for update skip locked
    limit p_limit
  )
  update public.publication_queue q
  set
    status = 'processing',
    attempts = q.attempts + 1,
    locked_at = now(),
    locked_by = p_worker_id,
    updated_at = now()
  from candidates c
  where q.id = c.id
  returning q.*;
end;
$$;

-- 8) Mark one claimed item as published and persist dedupe history atomically.
create or replace function public.complete_publication(
  p_queue_id uuid,
  p_worker_id text,
  p_external_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns public.publication_queue
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_row public.publication_queue;
begin
  update public.publication_queue q
  set
    status = 'published',
    external_id = coalesce(p_external_id, q.external_id),
    published_at = coalesce(q.published_at, now()),
    locked_at = null,
    locked_by = null,
    last_error = null,
    updated_at = now()
  where q.id = p_queue_id
    and q.status = 'processing'
    and q.locked_by = p_worker_id
  returning q.* into v_row;

  if v_row.id is null then
    raise exception 'queue item is not claimed by this worker';
  end if;

  insert into public.published_offers (
    source_queue_id, run_id, rule_id, offer_key, network, offer_id, channel,
    external_id, published_at, metadata
  ) values (
    v_row.id, v_row.run_id, v_row.rule_id, v_row.offer_key, v_row.network,
    v_row.offer_id, v_row.channel, v_row.external_id, v_row.published_at,
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (source_queue_id) where source_queue_id is not null
  do update set
    external_id = excluded.external_id,
    published_at = excluded.published_at,
    metadata = public.published_offers.metadata || excluded.metadata;

  insert into public.publication_logs (queue_id, run_id, rule_id, event, status, metadata)
  values (v_row.id, v_row.run_id, v_row.rule_id, 'published', v_row.status, coalesce(p_metadata, '{}'::jsonb));

  return v_row;
end;
$$;

-- 9) Release a claimed item as retry/failed with bounded backoff.
create or replace function public.fail_publication(
  p_queue_id uuid,
  p_worker_id text,
  p_error text,
  p_retry_after_seconds integer default null
)
returns public.publication_queue
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_row public.publication_queue;
begin
  if p_retry_after_seconds is not null and (p_retry_after_seconds < 0 or p_retry_after_seconds > 86400) then
    raise exception 'p_retry_after_seconds must be between 0 and 86400';
  end if;

  update public.publication_queue q
  set
    status = case when q.attempts >= q.max_attempts then 'failed' else 'retry' end,
    available_at = case
      when q.attempts >= q.max_attempts then q.available_at
      else now() + make_interval(secs => coalesce(
        p_retry_after_seconds,
        least(3600, (30 * power(2::numeric, greatest(q.attempts - 1, 0)))::integer)
      ))
    end,
    locked_at = null,
    locked_by = null,
    last_error = left(coalesce(p_error, 'unknown publication error'), 4000),
    updated_at = now()
  where q.id = p_queue_id
    and q.status = 'processing'
    and q.locked_by = p_worker_id
  returning q.* into v_row;

  if v_row.id is null then
    raise exception 'queue item is not claimed by this worker';
  end if;

  insert into public.publication_logs (queue_id, run_id, rule_id, event, status, message)
  values (
    v_row.id,
    v_row.run_id,
    v_row.rule_id,
    case when v_row.status = 'failed' then 'failed' else 'retry_scheduled' end,
    v_row.status,
    v_row.last_error
  );

  return v_row;
end;
$$;

-- 10) Service-only security model. No browser/user policies by design.
alter table public.automation_rules enable row level security;
alter table public.automation_runs enable row level security;
alter table public.publication_queue enable row level security;
alter table public.published_offers enable row level security;
alter table public.publication_logs enable row level security;

revoke all on table public.automation_rules from anon, authenticated;
revoke all on table public.automation_runs from anon, authenticated;
revoke all on table public.publication_queue from anon, authenticated;
revoke all on table public.published_offers from anon, authenticated;
revoke all on table public.publication_logs from anon, authenticated;

revoke all on sequence public.published_offers_id_seq from anon, authenticated;
revoke all on sequence public.publication_logs_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.automation_rules to service_role;
grant select, insert, update, delete on table public.automation_runs to service_role;
grant select, insert, update, delete on table public.publication_queue to service_role;
grant select, insert, update, delete on table public.published_offers to service_role;
grant select, insert, update, delete on table public.publication_logs to service_role;
grant usage, select on sequence public.published_offers_id_seq to service_role;
grant usage, select on sequence public.publication_logs_id_seq to service_role;

revoke execute on function public.set_updated_at() from public, anon, authenticated;
revoke execute on function public.recover_stale_publications(integer) from public, anon, authenticated;
revoke execute on function public.claim_due_publications(text, integer) from public, anon, authenticated;
revoke execute on function public.complete_publication(uuid, text, text, jsonb) from public, anon, authenticated;
revoke execute on function public.fail_publication(uuid, text, text, integer) from public, anon, authenticated;

grant execute on function public.recover_stale_publications(integer) to service_role;
grant execute on function public.claim_due_publications(text, integer) to service_role;
grant execute on function public.complete_publication(uuid, text, text, jsonb) to service_role;
grant execute on function public.fail_publication(uuid, text, text, integer) to service_role;

-- Prevent accidental browser exposure for future objects created by postgres in public.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, public;
